version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
  
executors:
  docker-executor:
    docker:
      - image: cimg/ruby:3.2.3-node
  ruby-executor:
    docker:
      - image: cimg/ruby:3.2.3-node

jobs:
  test:
    executor: ruby-executor
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Set up database
          command: |
            bundle exec rake db:create RAILS_ENV=test
            bundle exec rake db:schema:load RAILS_ENV=test
      - run:
          name: Run tests
          command: bundle exec rails test

  build:
    working_directory: ~/todo_list
    docker:
      - image: cimg/ruby:3.2.3-node
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
      - run:
          name: build-docker-image
          command: docker build -t $IMAGE_NAME:latest . --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE
          
      - run:
          name: publish-docker-image
          command: docker push $IMAGE_NAME
          
      - run:
          name: run-docker-image
          command: docker run -p 3000:3000 -d $IMAGE_NAME
          
  deploy:
    docker:
      - image: cimg/ruby:3.2.3-node
    steps:
      - run:
          name: deploy-application to ec2
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export CONTAINER_NAME=\"$CONTAINER_NAME\"; export IMAGE_NAME=\"$IMAGE_NAME\"; rm -rf ca-magic-cart/; git clone https://github.com/OrgGitMulc/ca-magic-cart; source ca-magic-cart/deploy.sh"
             
          
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches: 
              only:
                - main
      - build:
          filters:
            branches: 
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build